
import { config } from 'dotenv';
config(); // Load environment variables from .env file

import { getDb } from '@/lib/mongodb';
import clientPromise from '@/lib/mongodb'; // Import the clientPromise for closing the connection
import type { Destination } from '@/lib/types'; 
import { PLACEHOLDER_IMAGE_URL } from '@/lib/constants';


const TREK_DESTINATIONS_SEED_DATA: Omit<Destination, 'id'>[] = [
  // Uttarakhand
  { name: "Roopkund Trek", description: "A thrilling trek in Uttarakhand leading to the mysterious Roopkund Lake, known for the human skeletons found at its edge. Offers stunning views of Trishul and Nanda Ghunti peaks.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Himalayas", attractions: ["Roopkund Lake", "Bedni Bugyal", "Trishul Peak views", "Junargali Pass"], travelTips: "High altitude trek, requires excellent fitness and acclimatization. Best season: May-June, Aug-Sep.", averageRating: 4.7, coordinates: { lat: 30.257, lng: 79.723 }, aiHint: "uttarakhand roopkund trek" },
  { name: "Valley of Flowers & Hemkund Sahib", description: "A UNESCO World Heritage site, the Valley of Flowers is a vibrant expanse of alpine flora. Paired with a visit to the sacred Hemkund Sahib lake and Gurudwara.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Himalayas", attractions: ["Valley of Flowers National Park", "Hemkund Sahib Lake & Gurudwara", "Pushpawati River", "Diverse alpine flora"], travelTips: "Best visited during monsoon (July-August) for full bloom. Moderate difficulty. Ensure permits.", averageRating: 4.8, coordinates: { lat: 30.727, lng: 79.605 }, aiHint: "valley of flowers hemkund sahib" },
  { name: "Kedarkantha Trek", description: "A popular winter trek in Uttarakhand, known for its stunning 360-degree summit views of Himalayan peaks like Swargarohini and Bandarpoonch, often snow-covered.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Himalayas", attractions: ["Juda-ka-Talab", "Kedarkantha Peak summit", "Sankri village", "Govind National Park views"], travelTips: "Best done in winter (Dec-Apr) for snow. Suitable for beginners with good fitness. Requires warm clothing.", averageRating: 4.5, coordinates: { lat: 31.022, lng: 78.178 }, aiHint: "kedarkantha winter trek" },
  { name: "Har Ki Dun Trek", description: "Known as the 'Valley of Gods', this cradle-shaped valley in the Garhwal Himalayas offers stunning views of Swargarohini peaks, lush meadows, and traditional Garhwali villages like Osla.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["Har Ki Dun Valley", "Swargarohini Peak views", "Osla & Seema Villages", "Jaundhar Glacier (optional)"], travelTips: "Moderate trek, ideal for beginners to intermediate trekkers. Best seasons: April-June, September-November.", averageRating: 4.6, coordinates: { lat: 31.065, lng: 78.215 }, aiHint: "har ki dun uttarakhand" },
  // Himachal Pradesh
  { name: "Hampta Pass Trek", description: "A popular trek in Himachal Pradesh that offers a dramatic crossover from the lush green Kullu valley to the arid, stark landscapes of Lahaul. Features beautiful river crossings and camping at Shea Goru.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Himachal Pradesh, Himalayas", attractions: ["Chandratal Lake (optional extension)", "Shea Goru campsite", "Hampta Pass crossing (14,100 ft)", "Rohtang Pass views"], travelTips: "Moderate difficulty, suitable for beginners with good fitness. Best season: June-September.", averageRating: 4.6, coordinates: { lat: 32.270, lng: 77.395 }, aiHint: "himachal hampta pass" },
  { name: "Bhrigu Lake Trek", description: "A high-altitude alpine lake trek near Manali, Himachal Pradesh. The lake is believed to be the meditation spot of Sage Bhrigu and is known for its stunning blue waters and panoramic Himalayan views.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Himachal Pradesh, Himalayas", attractions: ["Bhrigu Lake", "Vashisht Village", "Views of Pir Panjal and Dhauladhar ranges", "Alpine meadows"], travelTips: "Moderate trek, can be done in 3-4 days. Best season: May-June, September-October. Acclimatize well.", averageRating: 4.5, coordinates: { lat: 32.300, lng: 77.220 }, aiHint: "bhrigu lake manali" },
  { name: "Beas Kund Trek", description: "A classic trek in Himachal Pradesh leading to Beas Kund, the source of the Beas River. Offers breathtaking close-up views of major peaks like Hanuman Tibba and Seven Sisters.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Himachal Pradesh, Himalayas", attractions: ["Beas Kund Glacier Lake", "Dhundi & Bakarthach campsites", "Solang Valley", "Views of Hanuman Tibba"], travelTips: "Easy to moderate trek, suitable for beginners. Best season: May-October.", averageRating: 4.4, coordinates: { lat: 32.395, lng: 77.065 }, aiHint: "beas kund himachal" },
  { name: "Kareri Lake Trek", description: "A serene trek in Himachal to the stunning freshwater Kareri Lake, nestled in the Dhauladhar range. The trail passes through lush forests, meadows, and shepherd villages.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Himachal Pradesh, Himalayas", attractions: ["Kareri Lake", "Kareri Village", "Nyund Nallah", "Dhauladhar views"], travelTips: "Moderate difficulty. Best seasons: April-June, September-November. Can be slippery post-monsoon.", averageRating: 4.3, coordinates: { lat: 32.388, lng: 76.277 }, aiHint: "kareri lake dhauladhar" },
  // Ladakh
  { name: "Markha Valley Trek", description: "A classic trek in Ladakh, often called 'tea house trek' due to homestay options. It traverses through remote villages, stunning canyons, high passes like Ganda La & Kongmaru La, with views of Kang Yatse peak.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Ladakh, Himalayas", attractions: ["Hemis National Park", "Ganda La (4900m)", "Kongmaru La (5200m)", "Markha River", "Ladakhi villages & monasteries"], travelTips: "Moderate to strenuous trek. Requires good acclimatization to high altitude. Best season: June-September.", averageRating: 4.7, coordinates: { lat: 33.875, lng: 77.430 }, aiHint: "ladakh markha valley" },
  { name: "Sham Valley Trek", description: "Known as the 'Baby Trek' of Ladakh, this is a relatively easier option to experience Ladakhi culture, ancient monasteries (Likir, Rizong, Temisgam), and beautiful arid landscapes.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Ladakh, Himalayas", attractions: ["Likir Monastery", "Rizong Monastery", "Temisgam Village", "Apricot orchards", "Views of Indus Valley"], travelTips: "Easy trek, ideal for beginners or families. Best season: May-October. Good for acclimatization.", averageRating: 4.2, coordinates: { lat: 34.250, lng: 77.200 }, aiHint: "ladakh sham valley trek" },
  { name: "Kang Yatse II & Stok Base Trek", description: "A challenging yet rewarding trek in Ladakh offering an ascent of Kang Yatse II (around 6250m) or views from Stok Kangri Base Camp. Provides a true high-altitude mountaineering experience.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Ladakh, Himalayas", attractions: ["Kang Yatse II summit views", "Stok Kangri Base Camp (views)", "Nimaling plains", "Ganda La & Kongmaru La (if part of Markha Valley approach)"], travelTips: "Strenuous, requires prior high-altitude trekking experience and excellent fitness. Proper acclimatization is critical. Best season: July-September.", averageRating: 4.8, coordinates: { lat: 33.900, lng: 77.550 }, aiHint: "kang yatse ladakh" },
  { name: "Lamayuru to Alchi Trek", description: "A cultural odyssey through Ladakh, connecting the ancient monasteries of Lamayuru and Alchi. The trail crosses remote passes and offers stunning views of the unique moonscape terrain.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Ladakh, Himalayas", attractions: ["Lamayuru Monastery ('Moonland')", "Alchi Monastery (UNESCO site)", "Wanla Monastery", "Prinkiti La pass"], travelTips: "Moderate trek, good for experiencing Ladakhi culture and history. Best season: June-September.", averageRating: 4.4, coordinates: { lat: 34.281, lng: 76.781 }, aiHint: "lamayuru alchi ladakh" },
  // Additional Uttarakhand Treks
  { name: "Satopanth Tal Trek", description: "A challenging trek to a high-altitude glacial lake of immense religious significance, nestled amidst towering peaks near Badrinath.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["Satopanth Tal Lake", "Views of Chaukhamba, Nilkantha, Swargarohini", "Laxmi Van", "Dhano Glacier"], travelTips: "Requires excellent fitness and prior high-altitude experience. Best season: May-June, September-October.", averageRating: 4.8, coordinates: { lat: 30.789, lng: 79.305 }, aiHint: "satopanth tal uttarakhand" },
  { name: "Rudranath Trek", description: "A spiritual trek to the Rudranath temple, one of the Panch Kedar, dedicated to Lord Shiva. Involves traversing beautiful meadows and forests.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["Rudranath Temple", "Anusuya Devi Temple", "Panar Bugyal", "Views of Nanda Devi, Trishul"], travelTips: "Moderate to difficult. Can be approached from multiple routes. Best season: May-June, September-October.", averageRating: 4.6, coordinates: { lat: 30.537, lng: 79.321 }, aiHint: "rudranath trek uttarakhand" },
  { name: "Tungnath - Chandrashila Trek", description: "A popular trek to the highest Shiva temple (Tungnath) and the Chandrashila summit, offering breathtaking 360-degree views of Himalayan peaks including Nanda Devi, Trishul, and Chaukhamba.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["Tungnath Temple", "Chandrashila Peak", "Deoriatal Lake (optional)", "Chopta meadows"], travelTips: "Relatively easy to moderate, suitable for beginners. Can be done year-round (snow in winter). Best views in spring and autumn.", averageRating: 4.7, coordinates: { lat: 30.487, lng: 79.217 }, aiHint: "tungnath chandrashila trek" },
  { name: "Vasuki Tal Trek", description: "A high-altitude trek near Kedarnath, leading to the pristine Vasuki Tal lake, surrounded by stunning views of Chaukhamba peaks.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["Vasuki Tal Lake", "Kedarnath Temple (nearby)", "Views of Chaukhamba peaks", "Glacial terrain"], travelTips: "Strenuous trek, requires good acclimatization. Best done post-monsoon: September-October.", averageRating: 4.5, coordinates: { lat: 30.770, lng: 79.098 }, aiHint: "vasuki tal kedarnath" },
  { name: "Gaumukh Tapovan Trek", description: "A revered trek to Gaumukh, the snout of the Gangotri Glacier and source of the Ganges river, followed by an ascent to Tapovan, a high-altitude meadow offering spectacular views of Mt. Shivling.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["Gaumukh (source of Ganges)", "Tapovan meadow", "Mt. Shivling views", "Gangotri Glacier", "Gangotri Temple"], travelTips: "Moderate to strenuous. Requires permits and acclimatization. Best season: May-June, September-October.", averageRating: 4.9, coordinates: { lat: 30.955, lng: 79.078 }, aiHint: "gaumukh tapovan trek" },
  { name: "Nag Tibba Trek", description: "A relatively easy weekend trek near Mussoorie, offering panoramic views of the Swargarohini, Bandarpoonch, Kedarnath, and Gangotri peaks. Ideal for beginners.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["Nag Tibba summit", "Pantwari village", "Views of Himalayan ranges", "Oak and rhododendron forests"], travelTips: "Easy to moderate, perfect for beginners and weekend trips. Can be done year-round.", averageRating: 4.3, coordinates: { lat: 30.596, lng: 78.123 }, aiHint: "nag tibba trek mussoorie" },
  { name: "Pindari Glacier Trek", description: "A classic trek in the Kumaon Himalayas leading to the Pindari Glacier, the source of the Pindar River. Offers stunning views of Nanda Devi and Nanda Kot.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Kumaon Himalayas", attractions: ["Pindari Glacier", "Zero Point", "Views of Nanda Devi, Nanda Kot", "Khati village", "Beautiful forests and river valleys"], travelTips: "Moderate difficulty. Best seasons: April-June, September-October.", averageRating: 4.6, coordinates: { lat: 30.257, lng: 79.970 }, aiHint: "pindari glacier kumaon" },
  { name: "Kuari Pass Trek", description: "Known as the Lord Curzon Trail, this trek offers magnificent views of Nanda Devi, Dronagiri, Kamet, and other Himalayan giants. Passes through lush meadows and dense forests.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["Kuari Pass", "Auli (ski resort)", "Joshimath", "Views of Nanda Devi sanctuary peaks", "Gorson Bugyal"], travelTips: "Moderate trek, suitable for beginners with good fitness. Best seasons: April-June, September-November. Winter snow trek option available.", averageRating: 4.7, coordinates: { lat: 30.517, lng: 79.600 }, aiHint: "kuari pass trek uttarakhand" },
  { name: "Brahmatal Trek", description: "A popular winter trek offering stunning views of Mt. Trishul and Nanda Ghunti, with the highlight being the frozen Brahmatal lake.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["Brahmatal Lake", "Bekaltal Lake", "Views of Mt. Trishul, Nanda Ghunti", "Rhododendron forests"], travelTips: "Moderate trek, ideal for winter. Requires warm clothing. Best season: December-March.", averageRating: 4.5, coordinates: { lat: 30.173, lng: 79.490 }, aiHint: "brahmatal winter trek" },
  { name: "Dayara Bugyal Trek", description: "A beautiful trek to one of Uttarakhand's largest alpine meadows, Dayara Bugyal, offering panoramic views of Himalayan peaks like Bandarpoonch and Gangotri range.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["Dayara Bugyal meadow", "Barnala Tal", "Raithal village", "Views of Bandarpoonch, Srikanth peaks"], travelTips: "Easy to moderate, suitable for beginners and families. Can be done year-round (snow in winter).", averageRating: 4.6, coordinates: { lat: 30.853, lng: 78.575 }, aiHint: "dayara bugyal trek" },
  { name: "Madhyamaheshwar Trek", description: "A serene trek to Madhyamaheshwar temple, one of the Panch Kedar, located in a beautiful valley with views of Chaukhamba, Kedarnath, and Neelkanth peaks.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["Madhyamaheshwar Temple", "Buda Madhyamaheshwar", "Ransi village", "Views of Chaukhamba"], travelTips: "Moderate difficulty. Best season: May-June, September-October.", averageRating: 4.5, coordinates: { lat: 30.638, lng: 79.223 }, aiHint: "madhyamaheshwar trek panch kedar" },
  { name: "Kalpeshwar Trek", description: "The only Panch Kedar temple accessible throughout the year. A relatively short and easy trek through beautiful landscapes.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["Kalpeshwar Temple", "Urgam Valley", "Dhyan Badri Temple"], travelTips: "Easy trek, suitable for all ages. Can be visited year-round.", averageRating: 4.2, coordinates: { lat: 30.579, lng: 79.457 }, aiHint: "kalpeshwar temple trek" },
  { name: "Panch Kedar Trek", description: "A comprehensive pilgrimage trek covering all five Kedar shrines: Kedarnath, Tungnath, Rudranath, Madhyamaheshwar, and Kalpeshwar. A challenging and spiritually rewarding journey.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["All five Kedar temples", "Varied landscapes from high mountains to lush valleys", "Spiritual significance"], travelTips: "Very strenuous and long duration. Requires excellent fitness, planning, and often guides. Best attempted in parts or by experienced trekkers. Season: May-June, Sep-Oct (avoiding monsoon).", averageRating: 4.9, coordinates: { lat: 30.600, lng: 79.200 }, aiHint: "panch kedar pilgrimage trek" },
  { name: "Bali Pass Trek", description: "A challenging high-altitude crossover trek connecting Har Ki Dun valley with Yamunotri. Offers stunning views and a true wilderness experience.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["Bali Pass (4950m)", "Ruinsara Tal", "Yamunotri Temple (descent)", "Views of Swargarohini, Bandarpoonch"], travelTips: "Strenuous and technical in parts. Requires prior high-altitude trekking experience and good fitness. Best season: June, September-October.", averageRating: 4.7, coordinates: { lat: 31.028, lng: 78.350 }, aiHint: "bali pass trek uttarakhand" },
  { name: "Dodital Trek", description: "A beautiful trek to the freshwater Dodital lake, believed to be the birthplace of Lord Ganesha. Surrounded by dense forests and offering serene Himalayan views.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["Dodital Lake", "Darwa Top (optional)", "Asi Ganga valley", "Sangam Chatti"], travelTips: "Easy to moderate trek, suitable for beginners and families. Best season: April-June, September-November.", averageRating: 4.4, coordinates: { lat: 30.842, lng: 78.489 }, aiHint: "dodital lake trek" },
  { name: "Auden's Col Trek", description: "An extremely challenging and technical high-altitude pass connecting Gangotri valley with Kedarnath valley. Considered one of the toughest treks in India.", imageUrl: PLACEHOLDER_IMAGE_URL(1200,600), country: "India", region: "Uttarakhand, Garhwal Himalayas", attractions: ["Auden's Col (5490m)", "Khatling Glacier", "Views of Gangotri and Jogin group of peaks", "Mayali Pass"], travelTips: "Highly strenuous and technical, requires mountaineering skills, equipment, and experienced guides. For expert trekkers only. Best season: May-June, September.", averageRating: 4.9, coordinates: { lat: 30.845, lng: 78.817 }, aiHint: "audens col trek" }
];

async function seedDatabase() {
  let mongoClient;
  try {
    const db = await getDb();
    mongoClient = await clientPromise; 
    const destinationsCollection = db.collection('destinations');
    
    // As per request, photos and stories are in Firebase, so we don't interact with them here.
    
    console.log('Successfully connected to MongoDB for destination seeding.');

    // Seed Destinations to MongoDB
    console.log('Clearing existing data from "destinations" collection in MongoDB...');
    await destinationsCollection.deleteMany({});
    console.log('Existing destination data cleared from MongoDB.');
    console.log(`Inserting ${TREK_DESTINATIONS_SEED_DATA.length} trek destinations into MongoDB...`);
    const destResult = await destinationsCollection.insertMany(TREK_DESTINATIONS_SEED_DATA);
    console.log(`${destResult.insertedCount} destinations successfully inserted into MongoDB.`);

    console.log('Database seeding for MongoDB destinations complete. Photos and stories are managed in Firebase.');

  } catch (error) {
    console.error('Error during MongoDB database seeding:', error);
    process.exit(1); 
  } finally {
    if (mongoClient) {
      console.log('Closing MongoDB connection...');
      await mongoClient.close();
      console.log('MongoDB connection closed.');
    }
  }
}

seedDatabase();
